version: "2"
services: 
  example: 
    build: .
    volumes:
      - ../:/app/
    environment:
      MICRO_REGISTRY_ADDRESS: "consul"

networks:
  default:
    external:
      name: microcompose_default